import { Product } from "./types/Product";

export const sampleProducts: Product [] = [
    {
        name: 'Nike Slim shirt',
        slug: 'Nike Slim shirt',
        category: 'shirt',
        image: '../images/p1.jpg',
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality shirt',
    },
    {
        name: 'Adidas Slim shirt',
        slug: 'Adidas Slim shirt',
        category: 'shirt',
        image: '../images/p2.jpg',
        price: 110,
        countInStock: 20,
        brand: 'Adidas',
        rating: 4.3,
        numReviews: 12,
        description: 'high quality shirt',
    },
    {
        name: 'Puma Slim shirt',
        slug: 'Puma Slim shirt',
        category: 'shirt',
        image: '../images/p3.jpg',
        price: 210,
        countInStock: 15,
        brand: 'Puma',
        rating: 4.6,
        numReviews: 14,
        description: 'high quality shirt',
    },
    {
        name: 'Gucci Slim shirt',
        slug: 'Gucci Slim shirt',
        category: 'shirt',
        image: '../images/p4.jpg',
        price: 125,
        countInStock: 13,
        brand: 'Gucci',
        rating: 4.0,
        numReviews: 2,
        description: 'high quality shirt',
    },
]